# Generated by Django 4.2.10 on 2024-03-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('every_30m', 'Every 30 min'), ('every_1m', 'Every min'), ('every_10m', 'Every 10 min'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('hourly', 'Hourly')], default='hourly', max_length=10),
        ),
    ]
